name: qb
services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    pull_policy: always
    container_name: qb
    network_mode: "ns:/run/netns/qb"
    environment:
      - "QBT_LEGAL_NOTICE=confirm"
    dns:
      # this points to the stub resolver running in host netns.
      # and it is capable of resolving both dn42 domain and clearnet domain.
      - "fd96:4158:7963::2"
    volumes:
      - "./qBittorrent:/config/qBittorrent/config"
      - "./downloads:/downloads"
      - "/root/seaweedfs-mount/downloads1:/downloads1"
      - "/root/wasabi-mount/qb-downloads:/downloads2"
    restart: unless-stopped
